Develop - Filmorate теперь больше площадка для фильмов
PanCakeOFF31/java-filmorate pull request #40
Opened 2024-04-08 03:20 UTC by PanCakeOFF31

На основании технического задания для проекта были определены новые функциональности, разделены между учатсниками команды и реализованы. 
Список функциональных возможностей:
1. Отзывы к фильма
2. Добавление режиссёров в фильм
3. Поиск фильма по критериям
4. Лента событий
5. Вывод самых популярных фильмов по жанру и годам
6.  Рекомендации фильмов
7.  Удаление фильмов и ползователей
8. Общие фильмы
Примечания:
1. Графическая схема БД лежит в папке main/resources/image/db_schema.png
2. Кан-бан: https://github.com/users/PanCakeOFF31/projects/1/views/1

2024-04-08 19:51 UTC, z8q requested changes

2024-04-08 19:51 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/friendship/FriendshipDbStorage.java
> +package ru.yandex.practicum.filmorate.storage.friendship;
Тут тоже ряд методов с вложенными селектами. 
Можно либо переписать на джойны, либо упростить запрос и логикой в коде сформировать нужные данные

2024-04-08 19:51 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/friendship/FriendshipDbStorage.java
> +package ru.yandex.practicum.filmorate.storage.friendship;
метод makeUser - private

2024-04-08 19:51 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    "(SELECT film_id FROM film_director WHERE director_id = ?)\n" +
Постараться избежать использования вложеенных селектов во всех методах

2024-04-08 19:51 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
>      public Film makeFilm(ResultSet rs) throws SQLException {
private

2024-04-08 19:51 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
>  @Component
Удается сохранить дубли фильмов

2024-04-08 19:51 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +    public Integer createDirector(Director director) {
Удается создать дубли директоров

2024-04-08 19:51 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<Film> getRecommendations(final int userId) {
Если сделать запрос для несуществующего пользователя, то ожидается ошибка UserNotFoundException с соответствующим текстом.

Но фактически получаем:

```JSON
{
	"error": "Ошибка выполнения SQL запроса",
	"description": "Проблемы связаны с пустым результатом запроса.",
	"methodMessage": "Incorrect result size: expected 1, actual 0"
}
```

2024-04-09 04:59 UTC, PanCakeOFF31 commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +package ru.yandex.practicum.filmorate.storage.mpa;
Статус: взял на исправление

2024-04-09 05:00 UTC, PanCakeOFF31 commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    public Review makeReview(ResultSet rs) throws SQLException {
Статус: взял на исправление

2024-04-09 05:00 UTC, PanCakeOFF31 commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewLikeDbStorage.java
> +                "(SELECT COUNT(*) FROM review_like WHERE review_id = ? AND is_like = false) AS useful";
Статус: взял на исправление

2024-04-09 05:03 UTC, PanCakeOFF31 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
>      public Film makeFilm(ResultSet rs) throws SQLException {
Статус: взял на исправление

2024-04-09 05:03 UTC, PanCakeOFF31 commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +    public Integer createDirector(Director director) {
Статус: взял на исправление

2024-04-09 05:49 UTC, PanCakeOFF31 commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +package ru.yandex.practicum.filmorate.storage.genre;
Статус: исправлено

2024-04-09 06:10 UTC, PanCakeOFF31 commented on src/main/java/ru/yandex/practicum/filmorate/storage/friendship/FriendshipDbStorage.java
> +package ru.yandex.practicum.filmorate.storage.friendship;
Статус: исправлено

2024-04-09 06:11 UTC, PanCakeOFF31 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    "(SELECT film_id FROM film_director WHERE director_id = ?)\n" +
Статус: принял на исправление

2024-04-09 06:11 UTC, PanCakeOFF31 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
>  @Component
Статус: принял на исправление

2024-04-09 08:28 UTC, MariaNzrv commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +            if (!usersFavoriteFilms.isEmpty() && usersFavoriteFilms.containsKey(userId)) {
Статус: в работе

2024-04-09 08:28 UTC, MariaNzrv commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +        SqlRowSet connectionRows = jdbcTemplate.queryForRowSet("select * from film_like");
Статус: в работе

2024-04-09 08:28 UTC, MariaNzrv commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<Film> getRecommendations(final int userId) {
Статус: в работе

2024-04-09 18:36 UTC, z8q approved these changes
Вы проделали большую работу! У вас получился отличный проект и появились навыки работы в команде. Здорово, что решили выполнить все пункты дополнительных задач. Правки сделали быстро, программа соответствует требованиям. Доработки принимаю)

2024-04-10 05:20 UTC, merged