№1 Sprint 9
PanCakeOFF31/java-filmorate pull request #7
Opened 2024-01-29 16:26 UTC by PanCakeOFF31

2024-01-29 20:30 UTC, z8q requested changes

2024-01-29 20:30 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank
Из доки NotBlank:
The annotated element must not be null and must contain at least one non-whitespace character.
То есть он проверяет на null тоже

2024-01-29 20:30 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    //    Последний тест от Яндекс "POST Create user with empty name" почему-то не содержит поле name
Из тз:
имя для отображения может быть пустым — в таком случае будет использован логин;
То есть в тесте предполагается, что если отправить объект без name, то мы запишем в name значение из login.

Посмотрел, у тебя такая проверка есть, только предварительно еще нужно проверить getName на null:
if (user.getName() == null || user.getName().isBlank())

2024-01-29 20:30 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank
NotBlank проверит на null тоже

2024-01-29 20:30 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Getter
Похоже getter добавлен для тестов.
В целом, делать доступ к мапе не очень хорошо, так как появляется возможность управления без использования логики в контроллере

2024-01-30 05:50 UTC, PanCakeOFF31 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    //    Последний тест от Яндекс "POST Create user with empty name" почему-то не содержит поле name
Странно, что в  Postman нет теста, на подобную ситуацию:

![2024-01-30_08-50-16](https://github.com/PanCakeOFF31/java-filmorate/assets/92355670/d0da0c77-0b3f-4c6f-8af2-5754f780859f)

2024-01-30 22:40 UTC, z8q approved these changes

2024-02-09 05:27 UTC, merged