Sprint #10
PanCakeOFF31/java-filmorate pull request #8
Opened 2024-02-13 10:26 UTC by PanCakeOFF31

2024-02-13 19:13 UTC, z8q requested changes

2024-02-13 19:13 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::getUserById)
Тут все ок, но когда будем работать с базами, нужно будет стараться избегать запросов в циклах или стримах. Отправлять запрос сразу со списком id например

2024-02-13 19:13 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    private String methodMessage = "";
тут есть необходимость в иниициализации поля?

2024-02-13 19:13 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            count = userStorage.getUsersQuantity();
Дублирующиеся userStorage.getUsersQuantity() можно вывести в переменную

2024-02-14 04:45 UTC, PanCakeOFF31 commented
"Я оставил несколько комментариев, но они больше для информации.
Работа выполнена хорошо, можно переотправить, я приму)"
Принимаю любые замечания микро и макро характера.

2024-02-14 05:00 UTC, PanCakeOFF31 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::getUserById)
Такая последовательность или не то понял: 1. Внутри запроса получить список друзей пользователя. 2. Взять у каждого пользователя id. 3. Сделать новый запрос на получение пользователей по id.

2024-02-14 05:03 UTC, PanCakeOFF31 commented
Так ж я заметил, что проверяю существования пользователя по id в 6 местах идентичным образом, но разное сообщение. Вывел это в один метод.

2024-02-14 18:29 UTC, z8q approved these changes

2024-02-14 18:29 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::getUserById)
Можно будет одним запросом получить список.
Ну идея в том, что есть например список id, нужно получить по нему пользователей.
Нужно стараться делать так, чтобы от количества id в списке не зависело количество обращений к базе

2024-02-15 07:33 UTC, merged