Add database
PanCakeOFF31/java-filmorate pull request #9
Opened 2024-02-29 17:42 UTC by PanCakeOFF31

2024-03-02 10:56 UTC, z8q requested changes

2024-03-02 10:56 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/films/FilmDbStorage.java
> +    public Integer addFilm(Film film) {
При повторной попытке добавления того же фильма приходит код 500.
Стоит обрабатывать исключение, возвращать сообщение, что фильм уже существует

2024-03-02 10:56 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/films/FilmDbStorage.java
> +    public Integer addFilm(Film film) {
Для user тоже применимо

2024-03-02 10:56 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/friendship/FriendshipDbStorage.java
> +    public boolean addToFriend(int userId, int friendId) {
Повторные запросы на добавления тоже дают ошибку с кодом 500, можно обработать.
Еще в табличке есть статус confirmed. Можно было бы устанавливать его в true, если пользователи добавили друг друга

2024-03-02 10:56 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/likes/LikeDbStorage.java
> +    public boolean like(int filmId, int userId) {
Ошибку повторного лайка тоже можно обработать)

2024-03-02 13:58 UTC, PanCakeOFF31 commented
Я добавил в  БД CHECK ограничения, чтобы точно не было ошибок. Если в логике пропустил, то последняя инстанция откажет.

2024-03-03 04:42 UTC, z8q approved these changes

2024-03-04 08:01 UTC, merged